{
 "title": "Routinator 0.9.0 and newer",
 "description": "This dashboard provides trust anchor and repository statistics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": "routinator_repository_publication_points_total"
   }
  ]
 },
 "panels": [
  { "title": "Repository Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Route Origin Attestations (ROAs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"roa\", state=\"valid\"}",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Validated ROA Payloads (VRPs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_contributed_vrps_total{uri=\"$repo\"}",
     "legendFormat": "Contributed (Valid minus Excluded)"
    }
   ]
  },
  {
   "title": "Valid Publication Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_publication_points_total{uri=\"$repo\", state=\"valid\"}",
     "legendFormat": "Valid Publication Points"
    },
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"manifest\", state=\"valid\"}",
     "legendFormat": "Valid Manifests"
    },
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"crl\", state=\"valid\"}",
     "legendFormat": "Valid CRLs"
    }
   ]
  },
  {
   "title": "CA Certificates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"ca_cert\", state=\"valid\"}",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Excluded VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_duplicate_vrps_total{uri=\"$repo\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "routinator_repository_locally_filtered_vrps_total{uri=\"$repo\"}",
     "legendFormat": "Locally Filtered"
    },
    {
     "expr": "routinator_repository_unsafe_vrps_total{uri=\"$repo\"}",
     "legendFormat": "Unsafe"
    }
   ]
  },
  {
   "title": "Rejected Publication Points",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_repository_publication_points_total{uri=\"$repo\", state=\"rejected\"}",
     "legendFormat": "Rejected Publication Points"
    },
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"manifest\", state=\"stale\"}",
     "legendFormat": "Stale Manifests"
    },
    {
     "expr": "routinator_repository_objects_total{uri=\"$repo\", type=\"crl\", state=\"invalid\"}",
     "legendFormat": "Invalid CRLs"
    }
   ]
  },
  {
   "title": "Update Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "routinator_rrdp_duration{uri=\"$repo\"}",
     "legendFormat": "RRDP"
    },
    {
     "expr": "routinator_rsync_duration{uri=\"$repo\"}",
     "legendFormat": "Rsync"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_rrdp_status{uri=\"$repo\"}",
     "legendFormat": "RRDP status code (200 = OK, 304 = Not Modified, 503 = Service Unavailable)"
    },
    {
     "expr": "routinator_rsync_status{uri=\"$repo\"}",
     "legendFormat": "rsync exit code (0 = Success, 10 = Error in socket I/O, 35 = Timeout waiting for daemon connection)"
    }
   ]
  },
  { "title": "Trust Anchor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RIPE NCC VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"ripe\"}"
    }
   ]
  },
  {
   "title": "APNIC VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"apnic\"}"
    }
   ]
  },
  { "title": "Uptime and VRP count", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 18, "y": 22 } },
  {
   "title": "ARIN VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"arin\"}"
    }
   ]
  },
  {
   "title": "LACNIC VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"lacnic\"}"
    }
   ]
  },
  {
   "title": "Last update duration",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "routinator_last_update_duration"
    }
   ]
  },
  {
   "title": "AFRINIC VRPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"afrinic\"}"
    }
   ]
  },
  {
   "title": "All VRPs (logarithmic scale)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"ripe\"}",
     "legendFormat": "RIPE NCC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"apnic\"}",
     "legendFormat": "APNIC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"lacnic\"}",
     "legendFormat": "LACNIC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"arin\"}",
     "legendFormat": "ARIN"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{job=\"routinator\",name=\"afrinic\"}",
     "legendFormat": "AFRINIC"
    }
   ]
  },
  {
   "title": "RTR Serial",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "routinator_serial{job=\"routinator\"}"
    }
   ]
  },
  {
   "title": "Total Validation Run Duration vs. RRDP or Rsync Update Time of Each Repo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "routinator_rsync_duration", "legendFormat": "{{uri}}" },
    { "expr": "routinator_rrdp_duration", "legendFormat": "{{uri}}" },
    {
     "expr": "routinator_last_update_duration",
     "legendFormat": "Total Time to Fetch Data + Cryptographic Validation"
    }
   ]
  },
  {
   "title": "rsync exit code (0 = Success, 10 = Error in socket I/O, 35 = Timeout waiting for daemon connection)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "routinator_rsync_status", "legendFormat": "{{uri}}" }
   ]
  },
  {
   "title": "RRDP exit code (200 = Success, -1 = Cannot Connect)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "routinator_rrdp_status", "legendFormat": "{{uri}}" }
   ]
  }
 ]
}